AICLOSURE-1 - backup and restore details added to support docs
AI4VBH/FLIP pull request #7
Opened 2022-11-18 11:13 UTC by jonanswer

2022-11-22 15:11 UTC, heyhaleema commented on documentation/support_docs.md
>  [TODO: List the Lambdas that we have defined and their purpose - dev team]
@jonanswer For the `TODO` comments in `[]`, could we remove these from the document/PR and raise corresponding issues instead? I feel like we'd be better able to track outstanding items and link these to future PRs, as well as keep the Jupyter Book clean whilst we're working on them.

2022-11-24 13:47 UTC, heyhaleema requested changes
@jonanswer Sorry for the belated review! Just a couple minor requested edits, but this looks good to merge 👍

2022-11-24 13:47 UTC, heyhaleema commented on documentation/support_docs.md
> +The [Data Catalogue](https://docs.google.com/spreadsheets/d/1wrFozOs4agLSqG4c0fS2YAsccVqQ4WMZWa2zVGOlJ0g/edit#gid=0) was compiled from the data requirements of the models shortlisted for deployment o
Can we move all external documents to (and therefore link in) this repo?

2022-12-01 09:43 UTC, jonanswer commented on documentation/support_docs.md
>  [TODO: List the Lambdas that we have defined and their purpose - dev team]
TODO comments now removed, the content they referred to should be added in as it becomes available

2022-12-01 09:44 UTC, jonanswer commented on documentation/support_docs.md
> +The [Data Catalogue](https://docs.google.com/spreadsheets/d/1wrFozOs4agLSqG4c0fS2YAsccVqQ4WMZWa2zVGOlJ0g/edit#gid=0) was compiled from the data requirements of the models shortlisted for deployment o
external docs moved in, all links repointed!

2022-12-01 13:31 UTC, merged